Adapt assertion to work on different architectures
This assertion was working well until recently. For some reason now it
doesn't work on macOS, where the error from LibXML is different from
what it was before.

On Debian 13 (Trixie), I can still see the error we have been expecting
for over a year:

```
Fatal error: Start tag expected, '<' not found at :1.
```

However, on macOS 15.7.4 (Sequoia) I am now seeing:

```
Fatal error: Document is empty at :1.
```

I'm guessing this is a change in the underlying libxml2. I can see
that on macOS I upgraded the library to 2.15.2 earlier this week
(using Homebrew) Perhaps this has a slightly different behaviour from
the 2.12.17 I have on Debian.